listening-port=3478
fingerprint
use-auth-secret
static-auth-secret=__TURN_SECRET__
realm=__STREAM_DOMAIN__
external-ip=__PUBLIC_IP__
min-port=49160
max-port=49200
stale-nonce=600
no-multicast-peers
no-tcp-relay
no-tls
log-file=stdout
simple-log
user-quota=4
total-quota=32
unauthorized-ratelimit
unauthorized-ratelimit-rps=10
